Cache ruller
bancodobrasil/featws-ruller pull request #96
Opened 2023-08-03 14:46 UTC by maycolacerda

Fix: Solved a problem that happened when the rulesheet version was defined as latest or not defined at all.

2023-08-03 16:25 UTC, eliasfeijo requested changes
Favor remover todos os `log.Print` de debug do arquivo `rulles.go`, e leia o comentário que fiz sobre o `.gitignore` para eu poder aprovar.

2023-08-03 16:25 UTC, eliasfeijo commented on .gitignore
> +listChangedFilesPathFromGit.sh
Acho que pode tirar esses 2 arquivos do ignore e commitar o `api.http`. O outro `.sh` não faz parte do projeto, então acho melhor tirar também...

2023-08-03 16:25 UTC, eliasfeijo commented on services/rulles.go
> +			ExpirationDate = time.Now().Add(time.Duration(s.expirationMultiplier) * time.Hour)
Favor remover logs de debug.

2023-08-03 18:04 UTC, maycolacerda commented on .gitignore
> +listChangedFilesPathFromGit.sh
feito.

2023-08-03 18:59 UTC, eliasfeijo requested changes
Faltaram alguns logs...

2023-08-03 18:59 UTC, eliasfeijo commented on services/rulles.go
> +	log.Printf("expirationMultiplier: %v", s.expirationMultiplier)
Faltaram esses também

2023-08-03 18:59 UTC, eliasfeijo commented on services/rulles.go
> +		log.Printf("Removing rule %v %v", key, element)
Outro aqui

2023-08-03 19:59 UTC, eliasfeijo approved these changes

2023-08-03 20:00 UTC, merged

2023-08-04 15:31 UTC, eduardacastro commented
Gente, criei o versão v2.1.10-rc1. Subi até desenv e continua o msm erro, nos primeiros momentos ele consegue pegar tanto com `latest` quanto sem versão e depois de um tempo ele para de funcionar.

Vou colocar as fotos nas cards